apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hinbert-fastapi.fullname" . }}
  labels: {{- include "hinbert-fastapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "hinbert-fastapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "hinbert-fastapi.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef: { name: {{ include "hinbert-fastapi.fullname" . }} }
            - secretRef: { name: {{ include "hinbert-fastapi.fullname" . }} }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          resources: {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet: { path: /health, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
