apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hinbert-fastapi.fullname" . }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secretKey | quote }}
  SMTP_PASSWORD: {{ .Values.smtpPassword | quote }}
