apiVersion: v1
kind: Service
metadata:
  name: {{ include "hinbert-fastapi.fullname" . }}
  labels: {{- include "hinbert-fastapi.labels" . | nindent 4 }}
spec:
  selector: {{- include "hinbert-fastapi.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
