"""complete_product_and_totp_fields

Revision ID: 97ed1bc05f4a
Revises: f8b632aa11da
Create Date: 2026-09-04 03:49:08.642114

This generated migration is reviewed source code. Keep schema changes small,
reversible, and paired with application compatibility during rollout.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "97ed1bc05f4a"
down_revision: str | Sequence[str] | None = "f8b632aa11da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the generated schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("category", sa.String(length=100), nullable=False, server_default="general"))
    op.add_column("products", sa.Column("owner_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    op.create_index(op.f("ix_products_owner_id"), "products", ["owner_id"], unique=False)
    with op.batch_alter_table("products", recreate="always") as batch_op:
        batch_op.create_foreign_key("fk_products_owner_id_users", "users", ["owner_id"], ["id"], ondelete="SET NULL")
    with op.batch_alter_table("totp_secrets") as batch_op:
        batch_op.add_column(sa.Column("encrypted_secret", sa.String(length=512), nullable=True))
        batch_op.drop_column("secret")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the generated schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("totp_secrets") as batch_op:
        batch_op.add_column(sa.Column("secret", sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column("encrypted_secret")
    with op.batch_alter_table("products") as batch_op:
        batch_op.drop_constraint("fk_products_owner_id_users", type_="foreignkey")
        batch_op.drop_index(op.f("ix_products_owner_id"))
        batch_op.drop_index(op.f("ix_products_category"))
        batch_op.drop_column("owner_id")
        batch_op.drop_column("category")
    # ### end Alembic commands ###
